name: Docker Build Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test Docker Build
        run: |
          docker build --build-arg SERVER_RELEASE_VERSION=${GITHUB_SHA} -t test-build .

